In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
# reading a tsv(tab separated values) file
file=pd.read_table("monkeypox_abstracts_dataset.tsv")
file.head()

ArticleId                                              Title  \
0   30981594  Human Monkeypox: Epidemiologic and Clinical Ch...   
1   34662033                                          Monkeypox   
2   33167496  Monkeypox Virus in Nigeria: Infection Biology,...   
3   24158414                                    Human monkeypox   
4   30445121  Vaccinating against monkeypox in the Democrati...   

                                            Abstract          NumberCitations  \
0  Recently, concern has been raised about the em...                       10   
1  Monkeypox virus was first isolated and identif...  Information Unavailable   
2  Monkeypox is a zoonotic disease caused by monk...                        3   
3  Human monkeypox is a zoonotic Orthopoxvirus wi...                       48   
4  Healthcare-associated transmission of monkeypo...                        5   

  PublicationType                                           Keywords  \
0          Review         Epidemic; Monkeypox; Smallpox; West Africa   
1            Book                            Information Unavailable   
2          Review  Nigeria; Poxviridae; antiviral drugs; epidemio...   
3          Review                 Orthopoxvirus; monkeypox; smallpox   
4          Review  Clinical trial; Democratic Republic of the Con...   

                               DOI  \
0        10.1016/j.idc.2019.03.001   
1          Information Unavailable   
2                10.3390/v12111257   
3               10.1093/cid/cit703   
4  10.1016/j.antiviral.2018.11.004   

                                             Authors  \
0  Petersen E, Kantele A, Koopmans M, Asogun D, Y...   
1                                  Moore M, Zahra F.   
2          Alakunle E, Moens U, Nchinda G, Okeke MI.   
3                             McCollum AM, Damon IK.   
4  Petersen BW, Kabamba J, McCollum AM, Lushima R...   

                                     JournalCitation  
0  Infect Dis Clin North Am. 2019 Dec;33(4):1027-...  
1  2022 May 22. In: StatPearls [Internet]. Treasu...  
2  Viruses. 2020 Nov 5;12(11):1257. doi: 10.3390/...  
3  Clin Infect Dis. 2014 Jan;58(2):260-7. doi: 10...  
4  Antiviral Res. 2019 Feb;162:171-177. doi: 10.1...

In [29]:
file['Abstract'][0]

'Recently, concern has been raised about the emergence of human monkeypox virus and the occasionally severe clinical presentation bearing resemblance to that of smallpox. In 2018 3 patients in the UK were diagnosed with monkeypox, and the frequency and geographic distribution of cases across West and Central Africa have increased in recent years. In Nigeria, most monkeypox patients are aged <40 years and lack cross-protective immunity because they were born after discontinuation of the smallpox eradication campaign. This article reviews the epidemiology, clinical features, and management of monkeypox and discusses its growing public health threat in this context.'

In [3]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   ArticleId        728 non-null    int64 
 1   Title            728 non-null    object
 2   Abstract         728 non-null    object
 3   NumberCitations  728 non-null    object
 4   PublicationType  728 non-null    object
 5   Keywords         728 non-null    object
 6   DOI              728 non-null    object
 7   Authors          728 non-null    object
 8   JournalCitation  728 non-null    object
dtypes: int64(1), object(8)
memory usage: 51.3+ KB


In [4]:
df=pd.read_csv("monkeypox_df.csv")
df.head()

ID     Status                             Location    City  Country  Age  \
0  1.0  confirmed  Guy's and St Thomas Hospital London  London  England  NaN   
1  2.0  confirmed  Guy's and St Thomas Hospital London  London  England  NaN   
2  3.0  confirmed                               London  London  England  NaN   
3  4.0  confirmed                               London  London  England  NaN   
4  5.0  confirmed                               London  London  England  NaN   

  Gender  Date_onset Date_confirmation        Symptoms  ...  \
0    NaN  2022-04-29        2022-05-06            rash  ...   
1    NaN  2022-05-05        2022-05-12            rash  ...   
2    NaN  2022-04-30        2022-05-13  vesicular rash  ...   
3   Male         NaN        2022-05-15  vesicular rash  ...   
4   Male         NaN        2022-05-15  vesicular rash  ...   

  Travel_history_country   Genomics_Metadata Confirmation_method  \
0                Nigeria  West African Clade              RT-PCR   
1                    NaN  West African Clade              RT-PCR   
2                    NaN  West African Clade              RT-PCR   
3                    NaN  West African Clade                 NaN   
4                    NaN  West African Clade                 NaN   

                                              Source  \
0  https://www.gov.uk/government/news/monkeypox-c...   
1  https://www.gov.uk/government/news/monkeypox-c...   
2  https://www.gov.uk/government/news/monkeypox-c...   
3  https://www.gov.uk/government/news/monkeypox-c...   
4  https://www.gov.uk/government/news/monkeypox-c...   

                                           Source_II  Date_entry  \
0  https://www.who.int/emergencies/disease-outbre...  2022-05-18   
1                                                NaN  2022-05-18   
2                                                NaN  2022-05-18   
3                                                NaN  2022-05-18   
4                                                NaN  2022-05-18   

   Date_last_modified Source_III Source_IV Country_ISO3  
0          2022-05-18        NaN       NaN          GBR  
1          2022-05-18        NaN       NaN          GBR  
2          2022-05-18        NaN       NaN          GBR  
3          2022-05-18        NaN       NaN          GBR  
4          2022-05-18        NaN       NaN          GBR  

[5 rows x 32 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1563 entries, 0 to 1562
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       1562 non-null   float64
 1   Status                   1562 non-null   object 
 2   Location                 603 non-null    object 
 3   City                     411 non-null    object 
 4   Country                  1562 non-null   object 
 5   Age                      273 non-null    object 
 6   Gender                   375 non-null    object 
 7   Date_onset               9 non-null      object 
 8   Date_confirmation        1226 non-null   object 
 9   Symptoms                 112 non-null    object 
 10  Hospitalised (Y/N/NA)    137 non-null    object 
 11  Date_hospitalisation     13 non-null     object 
 12  Isolated (Y/N/NA)        155 non-null    object 
 13  Date_isolation           10 non-null     object 
 14  Outcome                 

In [6]:
df['Status'].unique()

array(['confirmed', 'discarded', 'suspected', nan], dtype=object)

In [7]:
df['Symptoms'].unique()

array(['rash', 'vesicular rash', 'skin lesions, ulcerative lesions',
       'ulcerative lesions', nan, 'oral and genital ulcers, fever',
       'lesions', 'perianal papules; inguinal adenopathy',
       'genital ulcers', 'genital rash',
       'Slight swallowing difficulties and an elevated temperature',
       'fever, rash', 'skin rashes', 'fever, lesions', 'pustules, fever',
       'skin lesions', 'fever, cough, skin lesions',
       'fever, pustules on hands, body pains', 'blisters, high fever',
       'genital ulcer lesions', 'muscle aches, fever, skin lesions',
       'blisters', 'fever, skin lesions',
       'erythema with vesicles and papules, difficulty breathing, headache, fever',
       'skin lesions, spots on skin, severe anemia',
       'skin lesions, headaches, enlarged lymph nodes, fever',
       'fever, fatigue, headache, muscle pain',
       'skin rashes, dysphagia, muscle pain, fever, decreased physical strength, enlarged lymph nodes',
       'fever, outbreak on the sk

In [8]:
df['Age'].unique()

array([nan, '20-44', '30-59', '40-44', '25-29', '30-34', '40-49', '30-39',
       '50-59', '35-39', '20-64', '15-19', '<40', '55-59', '45-49',
       '20-24', '30-50', '50-54', '10-14', '70-74', '15-64', '60-64',
       '65-69', '25-44', '40-45', '26-54'], dtype=object)

In [9]:
df['Age'].fillna('Unknown',inplace=True)

In [10]:
df['Age'].unique()

array(['Unknown', '20-44', '30-59', '40-44', '25-29', '30-34', '40-49',
       '30-39', '50-59', '35-39', '20-64', '15-19', '<40', '55-59',
       '45-49', '20-24', '30-50', '50-54', '10-14', '70-74', '15-64',
       '60-64', '65-69', '25-44', '40-45', '26-54'], dtype=object)

In [11]:
df['Gender'].unique()

array([nan, 'Male', 'Female', 'CAN'], dtype=object)

In [12]:
df['Gender'].fillna("Unknown",inplace=True)

In [13]:
def symp_dict(row):
    symp_row=row
    symp_list=symp_row.split(",")
    if symp_row=="Unknown":
        score=0
    else:
        score=len(symp_list)
    return score

In [14]:
df['Symptoms'].fillna("Unknown",inplace=True)

In [15]:
df['Symp_count']=df['Symptoms'].apply(symp_dict)

In [16]:
df

ID     Status                             Location    City  \
0        1.0  confirmed  Guy's and St Thomas Hospital London  London   
1        2.0  confirmed  Guy's and St Thomas Hospital London  London   
2        3.0  confirmed                               London  London   
3        4.0  confirmed                               London  London   
4        5.0  confirmed                               London  London   
...      ...        ...                                  ...     ...   
1558  1558.0  confirmed                           California     NaN   
1559  1559.0  confirmed                             New York     NaN   
1560  1560.0  confirmed                             Illinois     NaN   
1561  1561.0  confirmed                 District of Columbia     NaN   
1562  1562.0  confirmed                               Hawaii     NaN   

            Country      Age   Gender  Date_onset Date_confirmation  \
0           England  Unknown  Unknown  2022-04-29        2022-05-06   
1           England  Unknown  Unknown  2022-05-05        2022-05-12   
2           England  Unknown  Unknown  2022-04-30        2022-05-13   
3           England  Unknown     Male         NaN        2022-05-15   
4           England  Unknown     Male         NaN        2022-05-15   
...             ...      ...      ...         ...               ...   
1558  United States  Unknown  Unknown         NaN        2022-06-08   
1559  United States  Unknown  Unknown         NaN        2022-06-08   
1560  United States  Unknown  Unknown         NaN        2022-06-08   
1561  United States  Unknown  Unknown         NaN        2022-06-08   
1562  United States  Unknown  Unknown         NaN        2022-06-08   

            Symptoms  ...   Genomics_Metadata Confirmation_method  \
0               rash  ...  West African Clade              RT-PCR   
1               rash  ...  West African Clade              RT-PCR   
2     vesicular rash  ...  West African Clade              RT-PCR   
3     vesicular rash  ...  West African Clade                 NaN   
4     vesicular rash  ...  West African Clade                 NaN   
...              ...  ...                 ...                 ...   
1558         Unknown  ...                 NaN                 NaN   
1559         Unknown  ...                 NaN                 NaN   
1560         Unknown  ...                 NaN                 NaN   
1561         Unknown  ...                 NaN                 NaN   
1562         Unknown  ...                 NaN                 NaN   

                                                 Source  \
0     https://www.gov.uk/government/news/monkeypox-c...   
1     https://www.gov.uk/government/news/monkeypox-c...   
2     https://www.gov.uk/government/news/monkeypox-c...   
3     https://www.gov.uk/government/news/monkeypox-c...   
4     https://www.gov.uk/government/news/monkeypox-c...   
...                                                 ...   
1558  https://www.cdc.gov/poxvirus/monkeypox/respons...   
1559  https://www.cdc.gov/poxvirus/monkeypox/respons...   
1560  https://www.cdc.gov/poxvirus/monkeypox/respons...   
1561  https://www.cdc.gov/poxvirus/monkeypox/respons...   
1562  https://www.cdc.gov/poxvirus/monkeypox/respons...   

                                              Source_II  Date_entry  \
0     https://www.who.int/emergencies/disease-outbre...  2022-05-18   
1                                                   NaN  2022-05-18   
2                                                   NaN  2022-05-18   
3                                                   NaN  2022-05-18   
4                                                   NaN  2022-05-18   
...                                                 ...         ...   
1558                                                NaN  2022-06-08   
1559                                                NaN  2022-06-08   
1560                                                NaN  2022-06-08   
1561                                        

In [17]:
df['Symp_count'].unique()

array([1, 2, 0, 3, 4, 6, 5], dtype=int64)

In [18]:
#drop few columns 
df.drop(columns=['Source','Source_II','Source_III','Source_IV'],inplace=True)

In [19]:
df.head()

ID     Status                             Location    City  Country  \
0  1.0  confirmed  Guy's and St Thomas Hospital London  London  England   
1  2.0  confirmed  Guy's and St Thomas Hospital London  London  England   
2  3.0  confirmed                               London  London  England   
3  4.0  confirmed                               London  London  England   
4  5.0  confirmed                               London  London  England   

       Age   Gender  Date_onset Date_confirmation        Symptoms  ...  \
0  Unknown  Unknown  2022-04-29        2022-05-06            rash  ...   
1  Unknown  Unknown  2022-05-05        2022-05-12            rash  ...   
2  Unknown  Unknown  2022-04-30        2022-05-13  vesicular rash  ...   
3  Unknown     Male         NaN        2022-05-15  vesicular rash  ...   
4  Unknown     Male         NaN        2022-05-15  vesicular rash  ...   

  Travel_history_entry Travel_history_start Travel_history_location  \
0           2022-05-04           late April  Lagos and Delta States   
1                  NaN                  NaN                     NaN   
2                  NaN                  NaN                     NaN   
3                  NaN                  NaN                     NaN   
4                  NaN                  NaN                     NaN   

  Travel_history_country   Genomics_Metadata Confirmation_method  Date_entry  \
0                Nigeria  West African Clade              RT-PCR  2022-05-18   
1                    NaN  West African Clade              RT-PCR  2022-05-18   
2                    NaN  West African Clade              RT-PCR  2022-05-18   
3                    NaN  West African Clade                 NaN  2022-05-18   
4                    NaN  West African Clade                 NaN  2022-05-18   

  Date_last_modified Country_ISO3 Symp_count  
0         2022-05-18          GBR          1  
1         2022-05-18          GBR          1  
2         2022-05-18          GBR          1  
3         2022-05-18          GBR          1  
4         2022-05-18          GBR          1  

[5 rows x 29 columns]

In [20]:
df.drop(columns='ID',inplace=True)

In [21]:
df['Status'].fillna('Unknown',inplace=True)

In [22]:
df['Status'].unique()

array(['confirmed', 'discarded', 'suspected', 'Unknown'], dtype=object)

In [23]:
df.loc[df['Status']=='confirmed','Status']='C'

In [24]:
df.loc[df['Status']=='discarded','Status']='D'
df.loc[df['Status']=='suspected','Status']='S'
df.loc[df['Status']=='Unknown','Status']='U'

In [25]:
df['Status'].unique()

array(['C', 'D', 'S', 'U'], dtype=object)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1563 entries, 0 to 1562
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Status                   1563 non-null   object 
 1   Location                 603 non-null    object 
 2   City                     411 non-null    object 
 3   Country                  1562 non-null   object 
 4   Age                      1563 non-null   object 
 5   Gender                   1563 non-null   object 
 6   Date_onset               9 non-null      object 
 7   Date_confirmation        1226 non-null   object 
 8   Symptoms                 1563 non-null   object 
 9   Hospitalised (Y/N/NA)    137 non-null    object 
 10  Date_hospitalisation     13 non-null     object 
 11  Isolated (Y/N/NA)        155 non-null    object 
 12  Date_isolation           10 non-null     object 
 13  Outcome                  1 non-null      object 
 14  Contact_comment         

In [27]:
df['Outcome'].unique()

array([nan, 'Recovered'], dtype=object)

In [28]:
df['Outcome'].value_counts()

Recovered    1
Name: Outcome, dtype: int64

In [ ]:
NLP, Text Clustering, Forecasting techniques.
Domain Study